"""
Case Processing Service

Handles post-retainer case lifecycle:
  Onboarding → Doc Collection → Form Prep → Review → Submit → Processing → Decision → Closed

Integrates with GHL Pipeline #2 (Case Processing) via tags + custom fields.
Program-aware: content (checklists, timelines, forms) loaded from config/programs.yaml.

Architecture: PostgreSQL is authoritative for case lifecycle data.
GHL gets a sync of case status for workflow triggers + operator visibility.
"""

import logging
import uuid
from datetime import datetime, timezone, timedelta
from typing import Optional

from app.services.ghl_client import GHLClient
from app.utils.compliance_log import log_event
from app.config_loader import load_yaml_config

logger = logging.getLogger("neuronx.cases")


def _load_programs_config() -> dict:
    """Load program definitions from YAML — single source of truth."""
    try:
        cfg = load_yaml_config("programs")
        return cfg.get("programs", {})
    except Exception as e:
        logger.warning("Failed to load programs config: %s — using empty defaults", e)
        return {}


def _get_processing_times(program_type: str) -> dict:
    """Get processing time estimate from config."""
    programs = _load_programs_config()
    for name, prog in programs.items():
        if name.lower() == program_type.lower():
            return prog.get("processing_months", {"min": 3, "max": 12, "avg": 6})
    return {"min": 3, "max": 12, "avg": 6}


def _get_ircc_forms(program_type: str) -> list:
    """Get required IRCC forms from config."""
    programs = _load_programs_config()
    for name, prog in programs.items():
        if name.lower() == program_type.lower():
            return prog.get("ircc_forms", [])
    return []


def _generate_case_id() -> str:
    """Generate collision-safe case ID: NX-YYYYMMDD-XXXXXXXX (UUID-based)."""
    now = datetime.now(tz=timezone.utc)
    unique = uuid.uuid4().hex[:8].upper()
    return f"NX-{now.strftime('%Y%m%d')}-{unique}"


class CaseService:
    """Manages case processing lifecycle and program-specific content."""

    def get_ircc_forms(self, program_type: str) -> list:
        """Get required IRCC forms for a program type from config."""
        return _get_ircc_forms(program_type)

    def get_processing_estimate(self, program_type: str) -> dict:
        """Get processing time estimate for a program type from config."""
        return _get_processing_times(program_type)

    async def initiate_case(self, contact_id: str, program_type: str, assigned_rcic: str) -> dict:
        """
        Start a new case after retainer is signed.
        Sets case fields, adds onboarding tag, generates doc checklist.
        """
        ghl = GHLClient()
        now = datetime.now(tz=timezone.utc)

        # Generate collision-safe case ID
        case_id = _generate_case_id()

        # Set doc collection deadline (14 days)
        deadline = now + timedelta(days=14)

        # Get processing time estimate from config
        proc_time = _get_processing_times(program_type)

        # Update GHL custom fields
        await ghl.update_custom_fields(contact_id, {
            "case_id": case_id,
            "case_program_type": program_type,
            "case_assigned_rcic": assigned_rcic,
            "case_assigned_at": now.strftime("%Y-%m-%d"),
            "case_deadline_date": deadline.strftime("%Y-%m-%d"),
            "case_deadline_type": "Doc Collection",
            "case_complexity": "Standard",
            "ircc_decision": "Pending",
        })

        # Add onboarding tag
        await ghl.add_tags(contact_id, ["nx:case:onboarding", "nx:case:docs_pending"])

        # Add case initiation note
        contact = await ghl.get_contact(contact_id)
        name = f"{contact.get('firstName', '')} {contact.get('lastName', '')}".strip()

        await ghl.add_note(contact_id, (
            f"CASE INITIATED — {case_id}\n"
            f"{'=' * 40}\n"
            f"Program: {program_type}\n"
            f"Assigned RCIC: {assigned_rcic}\n"
            f"Document deadline: {deadline.strftime('%Y-%m-%d')}\n"
            f"Estimated processing: {proc_time['min']}-{proc_time['max']} months\n"
            f"{'=' * 40}\n"
            f"Generated by NeuronX at {now.strftime('%Y-%m-%d %H:%M')} UTC"
        ))

        log_event("case_initiated", {
            "case_id": case_id,
            "contact_id": contact_id,
            "program_type": program_type,
            "assigned_rcic": assigned_rcic,
        })

        return {
            "case_id": case_id,
            "contact_id": contact_id,
            "program_type": program_type,
            "assigned_rcic": assigned_rcic,
            "doc_deadline": deadline.isoformat(),
            "estimated_processing_months": proc_time,
            "ircc_forms": _get_ircc_forms(program_type),
            "status": "onboarding",
        }

    async def update_stage(self, contact_id: str, new_stage: str, notes: Optional[str] = None) -> dict:
        """Update case stage via tag management."""
        ghl = GHLClient()

        # Map stage to tag
        stage_tags = {
            "onboarding": "nx:case:onboarding",
            "doc_collection": "nx:case:docs_pending",
            "docs_complete": "nx:case:docs_complete",
            "form_prep": "nx:case:form_prep",
            "under_review": "nx:case:under_review",
            "submitted": "nx:case:submitted",
            "processing": "nx:case:processing",
            "rfi": "nx:case:rfi",
            "decision": "nx:case:decision",
            "closed": "nx:case:closed",
        }

        tag = stage_tags.get(new_stage)
        if not tag:
            return {"error": f"Unknown stage: {new_stage}"}

        await ghl.add_tag(contact_id, tag)

        if notes:
            await ghl.update_custom_fields(contact_id, {"case_status_notes": notes})
            await ghl.add_note(contact_id, f"[CASE UPDATE] Stage: {new_stage}\n{notes}")

        log_event("case_stage_update", {
            "contact_id": contact_id,
            "new_stage": new_stage,
            "tag": tag,
        })

        return {"contact_id": contact_id, "stage": new_stage, "tag_added": tag}

    async def record_submission(self, contact_id: str, receipt_number: str, submission_date: Optional[str] = None) -> dict:
        """Record IRCC submission with receipt number."""
        ghl = GHLClient()
        now = datetime.now(tz=timezone.utc)

        sub_date = submission_date or now.strftime("%Y-%m-%d")

        await ghl.update_custom_fields(contact_id, {
            "ircc_receipt_number": receipt_number,
            "ircc_submission_date": sub_date,
            "case_deadline_date": (now + timedelta(days=30)).strftime("%Y-%m-%d"),
            "case_deadline_type": "IRCC Response",
        })

        await ghl.add_tag(contact_id, "nx:case:submitted")
        await ghl.add_note(contact_id, (
            f"[IRCC SUBMITTED]\n"
            f"Receipt #: {receipt_number}\n"
            f"Date: {sub_date}\n"
            f"Next milestone: IRCC response (est. 30 days)"
        ))

        log_event("ircc_submission", {
            "contact_id": contact_id,
            "receipt_number": receipt_number,
            "submission_date": sub_date,
        })

        return {"contact_id": contact_id, "receipt_number": receipt_number, "status": "submitted"}

    async def record_decision(self, contact_id: str, decision: str, decision_date: Optional[str] = None, notes: Optional[str] = None) -> dict:
        """Record IRCC decision (approved/refused/withdrawn/returned)."""
        valid_decisions = ["Approved", "Refused", "Withdrawn", "Returned", "Pending"]
        if decision not in valid_decisions:
            return {"error": f"Invalid decision: {decision}. Must be one of: {valid_decisions}"}

        ghl = GHLClient()
        now = datetime.now(tz=timezone.utc)
        dec_date = decision_date or now.strftime("%Y-%m-%d")

        await ghl.update_custom_fields(contact_id, {
            "ircc_decision": decision,
            "ircc_decision_date": dec_date,
            "case_status_notes": notes or f"IRCC decision: {decision}",
        })

        await ghl.add_tag(contact_id, "nx:case:decision")
        await ghl.add_note(contact_id, (
            f"[IRCC DECISION] {decision}\n"
            f"Date: {dec_date}\n"
            f"{notes or ''}"
        ))

        log_event("ircc_decision", {
            "contact_id": contact_id,
            "decision": decision,
            "decision_date": dec_date,
        })

        return {"contact_id": contact_id, "decision": decision, "status": "decision_recorded"}
